services:
  - type: web
    name: AvoinSuomi
    env: node
    buildCommand: |
      cd budjetinesitys && npm install && npm run build && cp -R dist/* ../budjetinesitysserveri/dist/
    startCommand: node budjetinesitysserveri/server.js
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000